---
# 確認用：execute-user
- name: check execute-user information
  shell: bash -lc "id"
  register: id

- name: print id (execute-user)
  debug:
    var: id

# yum update
- name: Run Yum Update
  yum:
    name: '*'
    state: latest

# Install：packages
- name: Install common packages
  yum:
    name: "{{ item }}"
    state: present #パッケージがシインストールされていない場合に任意のバージョンのものをインストール
  with_items:
    - gcc-c++
    - make
    - patch
    - git
    - curl
    - zlib-devel
    - openssl-devel
    - ImageMagick-devel
    - readline-devel
    - libcurl-devel
    - libffi-devel
    - libicu-devel
    - libxml2-devel
    - libxslt-devel
