# install Nginx using Ansible
# Start and Enable Nginx
# Check the status of Nginx
- name: Setup nginx server on target node
  hosts:
    - ansible-target01 # ターゲットノードを指定
  become: True # 特権モードで下記 roles 記述内容を実行

  roles:
    - web_server_role
  